name: CI - iOS
on:
  workflow_call:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ios-dependencies:
    runs-on: macos-14
    env:
      XCODE_VERSION: 16.1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate nitrogen code
        run: yarn nitrogen

      - name: Fix Nitrogen-generated Swift code
        run: ./scripts/fix-nitrogen-swift.sh

      - name: Build library first
        run: yarn prepare

      - name: Use appropriate Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Cache CocoaPods
        id: pods-cache
        uses: actions/cache@v4
        with:
          path: example/ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('example/ios/Podfile.lock', 'example/ios/Podfile', 'example/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Setup Ruby + Bundler cache
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: example

      - name: Install CocoaPods
        run: |
          cd example
          if [ "${{ steps.pods-cache.outputs.cache-hit }}" = "true" ]; then
            echo "Cache hit - verifying pod installation"
            if bundle exec pod check --project-directory=ios; then
              echo "✅ Pods are up to date"
            else
              echo "⚠️ Pods need update - running pod install"
              bundle exec pod install --project-directory=ios
            fi
          else
            echo "No cache hit - installing pods from scratch"
            rm -rf ios/Pods
            bundle exec pod install --project-directory=ios --repo-update
          fi

      - name: Verify iOS dependencies
        run: |
          cd example/ios
          echo "✅ iOS dependencies installed successfully"
          echo "Pods directory contents:"
          ls -la Pods/ | head -20
